<!DOCTYPE html>
<html>
    <head>
        <title>Example</title>
	</head>
    <body>
		<table border=1>
			<tr>
				<td>
					<h1>front atype doctype</h1>
				</td>
			</tr>
			<tr>
				<td>
					<a href='/order/index'>bbb</a>
					<?php echo self::display('layout') ?>

					<?php echo time();?>
					<?php echo 'a'. $a;?>
					0oop
				</td>
			</tr>
		</table>
    </body>
</html>
